lift_time:
	sec: 0 
	nanosec: 0

lift_name: 'lift_test'

available_floors: {'L1','L2'}
current_floor: 'L1'
destination_floor: 'L1'

door_state: 2
#uint8 DOOR_CLOSED=0
#uint8 DOOR_MOVING=1
#uint8 DOOR_OPEN=2

motion_state: 0
#uint8 MOTION_STOPPED=0
#uint8 MOTION_UP=1
#uint8 MOTION_DOWN=2
#uint8 MOTION_UNKNOWN=3

# We can only set human or agv mode, but we can read other modes: fire, etc.
available_modes: {0,1,2,3,4,5}
current_mode: 1
#uint8 MODE_UNKNOWN=0
#uint8 MODE_HUMAN=1
#uint8 MODE_AGV=2
#uint8 MODE_FIRE=3
#uint8 MODE_OFFLINE=4
#uint8 MODE_EMERGENCY=5
# we can add more "read-only" modes as we come across more of them.

# this field records the session_id that has been granted control of the lift
# until it sends a request with a request_type of REQUEST_END_SESSION
session_id: 'test'

