building_name: company
levels:
  L1:
    lanes:
    - - 0
      - 1
      - {}
    - - 1
      - 0
      - {}
    - - 1
      - 2
      - {}
    - - 2
      - 1
      - {}
    - - 2
      - 3
      - {}
    - - 3
      - 2
      - {}
    - - 3
      - 4
      - {}
    - - 4
      - 3
      - {}
    - - 5
      - 6
      - {}
    - - 6
      - 5
      - {}
    - - 3
      - 7
      - {}
    - - 7
      - 3
      - {}
    - - 7
      - 8
      - {}
    - - 8
      - 7
      - {}
    - - 9
      - 10
      - {}
    - - 10
      - 9
      - {}
    - - 11
      - 12
      - {}
    - - 12
      - 11
      - {}
    - - 8
      - 9
      - {}
    - - 9
      - 8
      - {}
    - - 4
      - 13
      - {}
    - - 13
      - 4
      - {}
    - - 13
      - 5
      - {}
    - - 5
      - 13
      - {}
    - - 13
      - 14
      - {}
    - - 14
      - 13
      - {}
    - - 14
      - 7
      - {}
    - - 7
      - 14
      - {}
    - - 14
      - 15
      - {}
    - - 15
      - 14
      - {}
    - - 15
      - 16
      - {}
    - - 16
      - 15
      - {}
    - - 16
      - 7
      - {}
    - - 7
      - 16
      - {}
    - - 16
      - 8
      - {}
    - - 8
      - 16
      - {}
    - - 2
      - 8
      - {}
    - - 8
      - 2
      - {}
    - - 3
      - 17
      - {}
    - - 17
      - 3
      - {}
    - - 15
      - 18
      - {}
    - - 18
      - 15
      - {}
    - - 10
      - 18
      - {}
    - - 18
      - 10
      - {}
    - - 18
      - 11
      - {}
    - - 11
      - 18
      - {}
    - - 9
      - 19
      - {}
    - - 19
      - 9
      - {}
    vertices:
    - - 77.88886289988827
      - -51.16819386034542
      - {name: '', spawn_robot_name: '', spawn_robot_type: ''}
    - - 77.42096648113957
      - -48.901292464442896
      - {name: ''}
    - - 79.01938136287028
      - -48.607690614618924
      - {is_charger: true, is_holding_point: true, is_parking_spot: true, name: tb3_0,
        spawn_robot_name: tb3_0, spawn_robot_type: robot_model}
    - - 78.23650615548955
      - -44.23645345186161
      - {name: ''}
    - - 76.01828616595819
      - -44.562656709838286
      - {is_charger: true, is_holding_point: true, is_parking_spot: true, name: tb3_2,
        spawn_robot_name: tb3_2, spawn_robot_type: robot_model}
    - - 70.92937661212557
      - -39.99568498053166
      - {name: ''}
    - - 73.80000311761029
      - -51.18477832909621
      - {name: ''}
    - - 84.17059302744735
      - -43.31415520110441
      - {name: ''}
    - - 85.54994158050785
      - -50.794696489961524
      - {is_holding_point: true, name: d}
    - - 96.49285330928872
      - -48.31320594136334
      - {name: ''}
    - - 95.15039416390584
      - -42.25192943643842
      - {is_holding_point: true, name: c}
    - - 101.6591990898361
      - -33.99387293960673
      - {is_holding_point: true, name: A}
    - - 103.04226811307262
      - -41.27558977990392
      - {is_holding_point: true, name: B}
    - - 75.288317305657
      - -37.64075347673518
      - {name: ''}
    - - 82.72988824589056
      - -36.23908210261848
      - {is_holding_point: true, name: f}
    - - 87.49007218908478
      - -35.32182855718472
      - {name: ''}
    - - 88.96981037808166
      - -42.5862042229326
      - {is_holding_point: true, name: e}
    - - 80.70847482278975
      - -41.086791683174326
      - {is_charger: true, is_holding_point: true, is_parking_spot: true, name: tb3_1,
        spawn_robot_name: tb3_1, spawn_robot_type: robot_model}
    - - 97.11618971081577
      - -33.46625982159187
      - {name: ''}
    - - 100.85513612009694
      - -47.526484146173495
      - {name: ''}
