coordinate_system: reference_image
crowd_sim:
  agent_groups:
    - {agents_name: [], agents_number: 0, group_id: 0, profile_selector: external_agent, state_selector: external_static, x: 0, y: 0}
  agent_profiles:
    - {ORCA_tau: 1, ORCA_tauObst: 0.4, class: 1, max_accel: 0, max_angle_vel: 0, max_neighbors: 10, max_speed: 0, name: external_agent, neighbor_dist: 5, obstacle_set: 1, pref_speed: 0, r: 0.25}
  enable: 0
  goal_sets: []
  model_types: []
  obstacle_set: {class: 1, file_name: L1_navmesh.nav, type: nav_mesh}
  states:
    - {final: 1, goal_set: -1, name: external_static, navmesh_file_name: ""}
  transitions: []
  update_time_step: 0.1
graphs:
  {}
levels:
  L1:
    drawing:
      filename: yanshi_1.png
    elevation: 0
    lanes:
      - [1, 3, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [3, 0, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [2, 1, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
    layers:
      {}
    measurements:
      - [5, 4, {distance: [3, 15.5]}]
    vertices:
      - [177.699, 135.059, 0, p_1, {is_holding_point: [4, true], is_parking_spot: [4, true]}]
      - [177.3, 91.17100000000001, 0, p_3, {is_holding_point: [4, true], is_parking_spot: [4, false]}]
      - [175.558, 80.97799999999999, 0, p_4, {is_holding_point: [4, false], pickup_dispenser: [1, pickup]}]
      - [177.034, 112.051, 0, p_2, {dropoff_ingestor: [1, dropoff], is_holding_point: [4, true]}]
      - [0, 310.001, 0, ""]
      - [0.001, 0.001, 0, ""]
lifts: {}
name: yanshi
